DROP TABLE IF EXISTS CropData;
CREATE TABLE CropData (id INTEGER PRIMARY KEY);
ALTER TABLE CropData ADD COLUMN lat Decimal(9,6);
ALTER TABLE CropData ADD COLUMN lng Decimal(9,6);
ALTER TABLE CropData ADD COLUMN type INTEGER(5);
ALTER TABLE CropData ADD COLUMN ct INTEGER(10)
