DROP TABLE IF EXISTS CropData;
CREATE TABLE CropData (id INTEGER PRIMARY KEY);
ALTER TABLE CropData ADD COLUMN longitude Decimal(9,6);
ALTER TABLE CropData ADD COLUMN latitude Decimal(9,6);
ALTER TABLE CropData ADD COLUMN type VARCHAR(256);
